### PR TITLE
fix(spectral): use kebab-case for paths

### PR DESCRIPTION
**Pull request by azetilov**
## Proposed Changes

- Use kebab-case for paths
- Use camelCase for template variables

API guidelines [naming conventions](https://github.com/adidas/api-guidelines/blob/master/rest-api-guidelines/evolution/naming-conventions.md#uri) specify using kebab-case for paths:

> Every URI MUST follow the General Rules except for the camelCase rule. Instead, a hyphen (-) SHOULD be used to delimit combined words (kebab-case).

According to [RFC6570](https://tools.ietf.org/html/rfc6570) URI template format is the following:
> URI-Template  = *( literals / expression )

Literals allowed characters: `(reserved / unreserved / pct-encoded)`

Hyphen `-` is unreserved character:
> unreserved     =  ALPHA / DIGIT / "-" / "." / "_" / "~"

Note however, according to RFC hyphen is NOT allowed in URI template variable list:
> expression    =  "{" [ operator ] variable-list "}"
```
     variable-list =  varspec *( "," varspec )
     varspec       =  varname [ modifier-level4 ]
     varname       =  varchar *( ["."] varchar )
     varchar       =  ALPHA / DIGIT / "_" / pct-encoded
```

That's why I propose to use camelCase there as we use it in parameter definitions.

### CODE REVIEW

**Comment by zdne** [comment]
> - Use kebab-case for paths
> - Use camelCase for template variables

This is correct, however, with my limited understanding to the spectral DSL shouldn't there be two rules: 

1. Rule for path that is `kebab-case` with the exception of template variables
2. Separate rule for parameters that are `in:path` so that they are `camelCase`

?

Thanks!

**Comment by jerzyn** [comment]
I second @zdne on the above :)

**Comment by azetilov** [comment]
Hey guys,
I created a separate rule for path parameters and adjusted the one for paths.
Thanks for pointing out!

Please review

**Comment by azetilov** [comment]
@jerzyn,
> I was thinking, whether this wouldn't be enough for the kebab-case paths:
>         match: "^(\/[a-z0-9-{}]+)+$"
Unfortunately, this regex does not cover the following cases:
```
/
/test/{helloWorld}
/test/{helloWorld}/sub
```

**Pull request merged**
